### ISSUE TITLE
Allow deleting applications

### ISSUE THREAD

**Issue by samjsharpe** [alphagov/release#11]
As a developer, I would like to delete applications from the release list. I may decide that an application I intended to create (and have added to the release app) is no longer required and hence I would like to delete it from the list.

If there are existing releases for this application, they should be retained in the database with corresponding information about what the application was, however the application itself should not appear on the Applications page.

If any new releases are made for that application, it should re-appear on the applications list automatically.

**Comment by tijmenb** [comment]
The archive feature's three year anniversary is coming up, so happily closing this.
