### ISSUE TITLE
Add a banner that indicates if it's not the canonical instance

### ISSUE THREAD

**Issue by jamiecobbett** [alphagov/release#17]
The govuk_select_organisation script deliberately doesn't switch the release app between staging and production because this would be very confusing when you're deploying.

It feels like a nice failsafe/courtesy to make it very obvious when you are on anything but the canonical instance.

I think the app has access to $ORGANISATION, so it could use that.

**Comment by tijmenb** [comment]
Fixed via https://github.com/alphagov/release/pull/64.
