### ISSUE TITLE
Display an application’s “in sync” status on its page

### ISSUE THREAD

**Issue by fatbusinessman** [alphagov/release#18]
On an [individual application’s page](https://release.production.alphagov.co.uk/applications/10), I would like it to be obvious whether the staging and production versions are the same, like it is in the application list.

**Comment by tijmenb** [comment]
Hello from the future.

This is visible on the application page:

<img width="1195" alt="screen shot 2016-11-16 at 11 59 00" src="https://cloud.githubusercontent.com/assets/233676/20346480/16579902-abf4-11e6-9aa9-728fd9732367.png">
 
And the deploy tag page:

<img width="1213" alt="screen shot 2016-11-16 at 11 58 28" src="https://cloud.githubusercontent.com/assets/233676/20346461/02b08daa-abf4-11e6-8bd8-403f83306177.png">
