### ISSUE TITLE
Request/claim a release slot from the app

### ISSUE THREAD

**Issue by fatbusinessman** [alphagov/release#28]
It would be good to be able to request a release slot from within the Release app.

One possible solution: in the commit log view, display a link to request a release for any tag ahead of the currently released version. This could potentially hook into the release calendar to show available deploy slots and/or to show when a release is scheduled for a given app.

![request-release](https://f.cloud.github.com/assets/32775/444181/b0f87216-b19c-11e2-9454-942ffc95c94e.png)

**Comment by cbaines** [comment]
GOV.UK isn't using release slots any more, so I'm closing this.
