### ISSUE TITLE
The list filter doesn’t work for the release app

### ISSUE THREAD

**Issue by dhwthompson** [alphagov/release#89]
The JavaScript list filtering works for most apps, but doesn’t work for the release app itself. The reason for this is that it filters on the contents of _any_ column, and so matches the `release_xxx` tags we record against the apps.

![release-app-release-bug](https://cloud.githubusercontent.com/assets/32775/6941711/00d2e284-d87a-11e4-9974-7ee98b20f0b9.gif)

**Comment by ChrisBAshton** [comment]
No longer a thing now that we don't use `release_x` tags.
